### ISSUE TITLE
Consider changing name to rollup-plugin-babili ?

### ISSUE THREAD

**Issue by boopathi** [Comandeer/rollup-plugin-babili#8]
I forgot I had the name `rollup-plugin-babili` on npm.

**Comment by Comandeer** [comment]
Actually I was trying to go with `rollup-plugin-babili`, but it was already taken, so I've added `real`.

It'll be very nice to have the shorter name.

**Comment by boopathi** [comment]
Cool. Added you (`comandeer`) on npm to `rollup-plugin-babili`. You can start publishing 👍 .

**Comment by Comandeer** [comment]
I've published actual 1.0.1 version (ok, with super tiny improvements ;)) under the new name. Thanks, @boopathi!
